apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sqs-prometheus-exporter
  namespace: demo
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: sqs-prometheus-exporter
  namespaceSelector:
    matchNames:
      - demo
  endpoints:
    - port: http
      path: /metrics
      interval: 30s