apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-api
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-api
  template:
    metadata:
      labels:
        app: checkout-api
    spec:
      containers:
      - name: app
        image: checkout-api:latest
        imagePullPolicy: Never
        env:
        - name: INVENTORY_SERVICE_URL
          value: "http://inventory-service" # Service Discovery name
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-api
  namespace: demo
  labels:
    app: inventory-service
spec:
  selector:
    app: checkout-api
  ports:
  - port: 80
    targetPort: 8080
    name: http