# --- CHECKOUT API (Go) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-api
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-api
  template:
    metadata:
      labels:
        app: checkout-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: app
        image: checkout-api:latest
        imagePullPolicy: Never
        env:
        - name: INVENTORY_SERVICE_URL
          value: "http://inventory-service" # Service Discovery name
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-api
  namespace: demo
spec:
  selector:
    app: checkout-api
  ports:
  - port: 80
    targetPort: 8080

# --- INVENTORY SERVICE (Python) ---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: app
        image: inventory-service:latest
        imagePullPolicy: Never
        env:
        - name: REDIS_HOST
          value: "redis-headless"
        - name: POSTGRES_DSN
          value: "dbname=postgres user=postgres password=postgres host=postgres-postgresql"
        - name: SQS_ENDPOINT
          value: "http://localstack.default.svc.cluster.local:4566"
        - name: SQS_QUEUE_URL
          value: "http://localstack.default.svc.cluster.local:4566/000000000000/orders-queue"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: demo
spec:
  selector:
    app: inventory-service
  ports:
  - port: 80
    targetPort: 8000

# --- SHIPPING WORKER (Go) ---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-worker
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-worker
  template:
    metadata:
      labels:
        app: shipping-worker
    spec:
      containers:
      - name: app
        image: shipping-worker:latest
        imagePullPolicy: Never
        env:
        - name: SQS_ENDPOINT
          value: "http://localstack.default.svc.cluster.local:4566"
        - name: SQS_QUEUE_URL
          value: "http://localstack.default.svc.cluster.local:4566/000000000000/orders-queue"